### PR TITLE
Docker build environment

### PR DESCRIPTION
**Pull request by ccheraa**
- `Dockerfile` to create the docker build environment's docker image
- The build uses a different `node_modules` folder to keep the user's `node_modules` content intact
- The user can pass the `UID` and `GID` to use while building.

### CODE REVIEW

**Comment by duncdrum** [comment]
@adamretter 
I m not sure what the usage scenario here is, and why we don't use e.g. `nano` images for win instead of `CentOS + WINE`, or simply run macOS and Win code in actual win or macOS environments on CI.  Signing similarly seems easier to handle via CI.

**Comment by adamretter** [comment]
@duncdrum This is not a runtime Docker Images.
This is the Docker Image for an environment which will compile binary releases of FusionStudio. Therefore a lot of libraries and development tools need to be present in the Image. This image is only for use by developers, not the end-users. Charaf is working on a separate Docker Image for a runtime environment for end-users.

**Comment by duncdrum** [comment]
I understand what it does, my question is why? What's the use case, and is this really the most efficient approach?:

1. It needs to run on mac with a valid certificate
2. universal builds for electron and VSC are just around the corner / out and we should aim to provide one too
2. it introduces further dependencies like wine with potential bugs and quirks

the alternative would be configure CI/**CD**  to handle this, then everybody with the right access conditions can do it from their phone. Without extra dependencies, using native WIN/nix/Xcode tools

**Comment by duncdrum** [comment]
given my recent foray into Orbs on CircleCI, and pending their response RE mac and win signing, we should reconsider this in light of CircleCIs capabilities.

**Comment by adamretter** [comment]
> I understand what it does, my question is why? What's the use case, and is this really the most efficient approach?:

Building FusionStudio requires a lot of dependencies and your environment setup in a certain way. Using a Docker image here instead means that anyone can build FusionStudio if they just have Docker and then therefore they don't need to try and get their local dependencies and environment correct.

This is also very useful for nightly builds, as we can run the Nightly Builds for FusionStudio in a Docker Container, meaning that we have a clean and isolated environment for every build.

> It needs to run on mac with a valid certificate

Not necessarily. You can code-sign the DMG after doing the build by moving it onto a Mac, we already do this for some nightly-build aspects.

Windows binaries themselves can be signed on Linux, you don't need Windows at all really.

> universal builds for electron and VSC are just around the corner / out and we should aim to provide one too

Do you mean Universal Binaries for macOS Apple Silicon and AMD64 Silicon? Or something else?

> it introduces further dependencies like wine with potential bugs and quirks

You have to have Wine if you want to build those Windows binaries from Linux. Otherwise, we would have to have a Windows Server which is available to build them for nightly builds. Cross-compiling from Linux to produce, Windows, Mac, and Linux binaries is the simplest option.

> the alternative would be configure CI/CD to handle this

Even if we use CI, we will likely want to provide a fixed build environment in the form of a Docker container ;-)

**NOTE**: We use an older CentOS as the base because it has an older glibc this means that the Linux binaries will run on the largest range of Linux distributions.

**Review by duncdrum — CHANGES_REQUESTED** [review]
i ve rebased these changes into #95 since there have been dependency updates in the interim. 

we should work on optimizations there.

found the docs comments was looking at the wrong readme

**Pull request closed without merging**
